#!/usr/bin/env bash
#
# Idempotent installer for cprec on a single Debian/Ubuntu host.
# No containers -- systemd units against a local PostgreSQL, per the
# deployment constraint.
#
# Usage:  sudo ./deploy/install.sh [--workers N]
#
set -euo pipefail

WORKERS=2
while [[ $# -gt 0 ]]; do
    case "$1" in
        --workers) WORKERS="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

[[ $EUID -eq 0 ]] || { echo "run as root" >&2; exit 1; }

APP_DIR=/opt/cprec
CONF_DIR=/etc/cprec
PG_VERSION=17

echo "==> packages"
apt-get update -qq
# postgresql-contrib supplies pg_trgm, which the CDR search indexes require --
# the migration fails without it.
apt-get install -y -qq \
    "postgresql-${PG_VERSION}" "postgresql-contrib-${PG_VERSION}" \
    python3-venv python3-dev build-essential libpq-dev \
    nginx ffmpeg curl ca-certificates git

echo "==> service account"
id -u cprec &>/dev/null || useradd --system --home-dir "$APP_DIR" --shell /usr/sbin/nologin cprec

echo "==> directories"
install -d -o cprec -g cprec -m 0755 "$APP_DIR" /var/lib/cprec /var/lib/cprec/spool
install -d -o cprec -g cprec -m 0750 /var/cache/cprec /var/cache/cprec/transcode /var/log/cprec
install -d -o root  -g cprec -m 0750 "$CONF_DIR"

echo "==> master key"
# Losing this file makes every stored S3 credential unrecoverable, so it is
# generated once and never regenerated by this script.
if [[ ! -f "$CONF_DIR/master.key" ]]; then
    python3 -c 'import os,base64;print(base64.urlsafe_b64encode(os.urandom(32)).decode())' \
        > "$CONF_DIR/master.key"
    chown root:root "$CONF_DIR/master.key"
    chmod 0600 "$CONF_DIR/master.key"
    echo "    generated $CONF_DIR/master.key -- BACK THIS UP SEPARATELY FROM THE DATABASE"
else
    echo "    keeping existing $CONF_DIR/master.key"
fi

echo "==> database"
DB_PASS_FILE="$CONF_DIR/db_password"
if [[ ! -f "$DB_PASS_FILE" ]]; then
    python3 -c 'import secrets;print(secrets.token_urlsafe(32))' > "$DB_PASS_FILE"
    chmod 0600 "$DB_PASS_FILE"
fi
DB_PASS="$(cat "$DB_PASS_FILE")"

systemctl enable --now postgresql
# The application role is deliberately NOT a superuser and does NOT hold
# BYPASSRLS: either would bypass the brand-isolation policies entirely.
sudo -u postgres psql -qtA <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cprec') THEN
        CREATE ROLE cprec LOGIN PASSWORD '${DB_PASS}';
    ELSE
        ALTER ROLE cprec PASSWORD '${DB_PASS}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cprec_platform') THEN
        CREATE ROLE cprec_platform LOGIN PASSWORD '${DB_PASS}' BYPASSRLS;
    ELSE
        ALTER ROLE cprec_platform PASSWORD '${DB_PASS}' BYPASSRLS;
    END IF;
END \$\$;
SELECT 'CREATE DATABASE cprec OWNER cprec'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'cprec')\gexec
SQL
sudo -u postgres psql -d cprec -qc "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
sudo -u postgres psql -d cprec -qc "GRANT ALL ON SCHEMA public TO cprec;"

echo "==> bootstrap configuration"
# There is no application config file. Every setting lives in the database and
# is edited in the UI (Settings) or with `cprec-admin settings set`. The only
# thing written here is how to reach the database, because that is what a
# process needs before it can read anything else.
cat > "$CONF_DIR/database.env" <<ENVEOF
CPREC_DATABASE_URL=postgresql+asyncpg://cprec:${DB_PASS}@127.0.0.1:5432/cprec
CPREC_PLATFORM_DATABASE_URL=postgresql+asyncpg://cprec_platform:${DB_PASS}@127.0.0.1:5432/cprec
ENVEOF
chown root:root "$CONF_DIR/database.env"
chmod 0600 "$CONF_DIR/database.env"

# Remove config files from earlier layouts so nothing reads stale values.
rm -f "$CONF_DIR/cprec.env" "$CONF_DIR/secrets.env"

echo "==> python environment"
if [[ ! -x "$APP_DIR/.venv/bin/python" ]]; then
    sudo -u cprec python3 -m venv "$APP_DIR/.venv"
fi
sudo -u cprec "$APP_DIR/.venv/bin/pip" install --quiet --upgrade pip
sudo -u cprec "$APP_DIR/.venv/bin/pip" install --quiet -e "$APP_DIR"

echo "==> migrations"
cd "$APP_DIR"
sudo -u cprec env \
    CPREC_DATABASE_URL="postgresql+asyncpg://cprec:${DB_PASS}@127.0.0.1:5432/cprec" \
    CPREC_MASTER_KEY="$(cat "$CONF_DIR/master.key")" \
    "$APP_DIR/.venv/bin/alembic" upgrade head

echo "==> systemd units"
install -m 0644 deploy/systemd/*.service deploy/systemd/*.target /etc/systemd/system/
systemctl daemon-reload

echo "==> nginx"
install -m 0644 deploy/nginx/cprec_proxy_params.conf /etc/nginx/
install -m 0644 deploy/nginx/cprec.conf /etc/nginx/sites-available/cprec.conf
ln -sf /etc/nginx/sites-available/cprec.conf /etc/nginx/sites-enabled/cprec.conf
if nginx -t 2>/dev/null; then
    systemctl reload nginx
else
    echo "    nginx config not valid yet (TLS certificate and server_name still to set);"
    echo "    edit /etc/nginx/sites-available/cprec.conf then: nginx -t && systemctl reload nginx"
fi

echo "==> services"
# Scheduler and reconciler are singletons on purpose -- each takes a PostgreSQL
# advisory lock and a second instance exits rather than double-queueing scans.
# Workers are the scaling knob.
systemctl enable --now cprec-api cprec-scheduler cprec-reconciler
for i in $(seq 1 "$WORKERS"); do systemctl enable --now "cprec-worker@${i}"; done

echo
echo "Installed. Next steps:"
echo
echo "  1. Create the administrator (local account; AD/Entra can be added later):"
echo "       sudo -u cprec CPREC_DATABASE_URL=... CPREC_MASTER_KEY_FILE=$CONF_DIR/master.key \\"
echo "         $APP_DIR/.venv/bin/cprec-admin superadmin create --email you@example.com"
echo
echo "  2. Add a brand per company, so their data can never mix:"
echo "       cprec-admin brand add --name 'Go4Rex' --slug go4rex"
echo
echo "  3. Add tenants and CommPeak connections (credentials are prompted for and"
echo "     sealed; nothing is written to or deleted from CommPeak, ever):"
echo "       cprec-admin tenant add --brand go4rex --name '<domain>' --slug <slug>"
echo "       cprec-admin connection add --brand go4rex --tenant <slug> --name '...' --bucket <uuid>"
echo
echo "  4. CommPeak requires this server's public IP on each account's ACL:"
echo "       $(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo '<could not detect>')"
echo
echo "  5. Everything else is configured in the web UI under Settings, or with"
echo "     'cprec-admin settings set'. Transfers stay off until an archive"
echo "     destination exists and transfer.enabled is turned on."
echo
echo "  6. Back up $CONF_DIR/master.key somewhere the database backup is NOT."
echo "     Without it, every stored credential is unrecoverable."
echo
echo "  Verify: cprec-admin doctor && curl -fsS localhost:8000/api/health"
